version: '3'

tasks:
  build:
    cmds:
      - go-winres make --in ./winres.json
      - go build -o ./output/ezstore.exe
      - iscc "setup.iss"

  test:
    cmds:
      - go test ./...

  lint:
    cmds:
      - go vet
      - staticcheck .
