name: 'Teardown'
runs:
  using: 'composite'
  steps:
    - uses: actions/cache/save@v4
      with:
        path: |
          %USERPROFILE%\go
          %LocalAppData%\go-build
          %LocalAppData%\golangci-lint
        key: ${{ runner.os }}-${{ runner.arch }}-go-${{ hashFiles('.\go.mod', '.\.build\go.mod', '.\.build\golangci-lint\go.mod') }}
