name: Check and test

on:
  pull_request:
    paths-ignore:
      - '.vscode/**'
      - '.idea/**'
      - 'icons/**'

jobs:
  check-and-test:
    runs-on: windows-latest

    name: Check and test project

    steps:
      - uses: actions/checkout@v4

      - name: Restore cache
        uses: actions/cache/restore@v4
        with:
          path: |
            C:\Users\runneradmin\go
            C:\Users\runneradmin\AppData\Local\go-build
          key: cache-go-${{ hashFiles( 'C:\Users\runneradmin\{go,AppData\Local\go-build}\**' ) }}

      - name: Setup GO
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: false

      - name: Download project dependencies
        run: go get .\...

      - name: Setup staticcheck@latest
        run: |
          go install "honnef.co/go/tools/cmd/staticcheck@latest"

      - name: Check project
        run: .\run.ps1 check

      - name: Run unit tests
        run: .\run.ps1 test

      - name: Restore cache
        uses: actions/cache/save@v4
        with:
          path: |
            C:\Users\runneradmin\go
            C:\Users\runneradmin\AppData\Local\go-build
          key: cache-go-${{ hashFiles( 'C:\Users\runneradmin\{go,AppData\Local\go-build}\**' ) }}
