name: Check and test

on:
  pull_request:
    branches:
      - 'main'
    paths-ignore:
      - '.vscode/**'
      - '.idea/**'
      - 'icons/**'

jobs:
  check-and-test:
    runs-on: windows-latest

    name: Check and test project

    steps:
      - uses: actions/checkout@v4

      - uses: kenchan0130/actions-system-info@v1.3.1
        id: system-info

      - name: Restore cache
        uses: actions/cache/restore@v4
        with:
          path: |
            ~\go
            ~\AppData\Local\go-build
          key: ${{ runner.os }}-${{ steps.system-info.outputs.release }}-go-${{ github.job }}-${{ hashFiles( './go.sum' ) }}
          restore-keys: |
            ${{ runner.os }}-${{ steps.system-info.outputs.release }}-go-${{ github.job }}-

      - name: Setup GO
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: false

      - name: Download project dependencies
        run: go mod download

      - name: Check project
        run: .\run.ps1 check

      - name: Run unit tests
        run: .\run.ps1 test

      - name: Restore cache
        uses: actions/cache/save@v4
        with:
          path: |
            ~\go
            ~\AppData\Local\go-build
          key: ${{ runner.os }}-${{ steps.system-info.outputs.release }}-go-${{ github.job }}-${{ hashFiles( './go.sum' ) }}
