name: Check and test

on:
  pull_request:
    paths-ignore:
      - '.vscode/**'
      - '.idea/**'
      - 'icons/**'

jobs:
  check-and-test:
    runs-on: windows-latest

    name: Check and test project

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Setup staticcheck@2025.1.1
        uses: mattdowdell/go-installer@v0.3.0
        with:
          package: honnef.co/go/tools/cmd/staticcheck
          version: 2025.1.1

      - name: Check project
        run: .\run.ps1 check

      - name: Run unit tests
        run: .\run.ps1 test
