name: Check and test

on:
  pull_request:
    paths-ignore:
      - '.vscode/**'
      - '.idea/**'
      - 'icons/**'

jobs:
  check-and-test:
    runs-on: windows-latest

    name: Check and test project

    steps:
      - uses: actions/checkout@v4

      - uses: .github/workflows/setup-go.yaml

      - name: Download project dependencies
        run: go get .\...

      - name: Setup staticcheck@latest
        run: |
          go install "honnef.co/go/tools/cmd/staticcheck@latest"

      - name: Check project
        run: .\run.ps1 check

      - name: Run unit tests
        run: .\run.ps1 test

      - uses: .github/workflows/teardown-go.yaml
