name: Check and test

on:
  pull_request:
    branches:
      - 'main'
    paths-ignore:
      - '.vscode/**'
      - '.idea/**'
      - 'icons/**'

jobs:
  check-and-test:
    runs-on: windows-latest

    name: Check and test project

    steps:
      - uses: actions/checkout@v4

      - id: init
        uses: ./.github/actions/init

      - name: Check project
        run: .\run.ps1 check

      - name: Run unit tests
        run: .\run.ps1 test

      - uses: ./.github/actions/teardown
        with:
          path: ${{ steps.init.outputs.path }}
          key: ${{ steps.init.outputs.key }}
