name: E2e tests

on:
  workflow_dispatch:
    inputs:
      target-ref:
        description: The branch, tag or SHA to checkout.
        type: string
  push:
    branches:
      - "main"
    paths:
      - '.github/actions/**'
      - '.github/workflows/e2e-tests.yaml'
      - '.build/**'
      - '**.go'
      - '**.mod'
      - '**.sum'
      - 'internal/**'
      - 'tests/**'
      - 'run.ps1'
  pull_request:
    branches:
      - 'main'
    paths:
      - '.github/actions/**'
      - '.github/workflows/e2e-tests.yaml'
      - '.build/**'
      - '**.go'
      - '**.mod'
      - '**.sum'
      - 'internal/**'
      - 'tests/**'
      - 'run.ps1'

jobs:
  build:
    name: Build

    runs-on: windows-latest

    steps:
      - name: Setting target ref
        id: ref
        run: |
          if ( "true" -eq "${{ inputs.target-ref == '' }}" ) {
            $Ref = "main";
          } else {
            $Ref = "${{ inputs.target-ref }}"
          }
          echo "Ref is '$Ref'";
          echo "target-ref=$Ref" >> $env:GITHUB_OUTPUT;

      - uses: actions/checkout@v4
        with:
          ref: ${{ steps.ref.outputs.target-ref }}
          fetch-depth: 0

      - name: Setup GO
        uses: ./.github/actions/setup-go

      - name: Build project
        run: .\run.ps1 build

      - name: Save cache
        if: always()
        uses: ./.github/actions/save-cache

      - name: Upload app
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: output

  test:
    needs: build

    strategy:
      fail-fast: false
      matrix:
        include:
          - label: windows-2022
            name: Windows 10 2022 x64
            archs: amd64,386
            path: .\output
          - label: windows-2025
            name: Windows 10 2025 x64
            archs: amd64,386
            path: .\output
          - label: windows-11-arm
            name: Windows 11 ARM
            archs: arm64,amd64
            path: .\output

    runs-on: ${{ matrix.label }}

    name: ${{ matrix.archs }} | ${{ matrix.name }}

    steps:
      - uses: actions/checkout@v4

      - name: Download app
        uses: actions/download-artifact@v4
        with:
          name: build
          path: output

      - name: Running tests
        shell: pwsh
        run: .\tests\All.ps1 -Path "${{ matrix.path }}" -Archs "${{ matrix.archs }}"
