name: E2e tests

on:
  workflow_dispatch:
    inputs:
      target-ref:
        description: The branch, tag or SHA to checkout.
        type: string
  push:
    branches:
      - "main"
    paths:
      - '.github/actions/**'
      - '.github/workflows/e2e-tests.yaml'
      - '.mage/**'
      - '**.go'
      - '**.mod'
      - '**.sum'
      - 'internal/**'
      - 'tests/**'
      - 'run.ps1'

jobs:
  build:
    name: Build

    runs-on: windows-latest

    steps:
      - name: Setting target ref
        id: ref
        run: |
          if ( "true" -eq "${{ inputs.target-ref == '' }}" ) {
            $Ref = "main";
          } else {
            $Ref = "${{ inputs.target-ref }}"
          }
          echo "Ref is '$Ref'";
          echo "target-ref=$Ref" >> $env:GITHUB_OUTPUT;

      - uses: actions/checkout@v4
        with:
          ref: ${{ steps.ref.outputs.target-ref }}
          fetch-depth: 0

      - name: Setup GO
        uses: ./.github/actions/setup-go

      - name: Build project
        run: .\run.ps1 build

      - name: Save cache
        if: always()
        uses: ./.github/actions/save-cache

      - name: Upload app
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: output

  generation:
    runs-on: windows-latest

    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:
      - uses: actions/checkout@v4

      - name: Generating matrix
        id: set-matrix
        run: |
          $Data = Get-Content -Raw '.\.github\matrix.json' | ConvertFrom-Json;
          $Include = @();

          foreach ( $Target in $Data.targets ) {
            foreach ( $Os in $Data.os ) {
              if ( $Target.label -eq $Os.label ) {
                $Include += @{
                  label = $Os.label
                  name = "'$($Target.scenario)' on $($Os.name)"
                  run = ".\tests\$($Target.scenario).ps1"
                };
              }
            }
          }

          foreach ( $Install in $Data.install ) {
            $Target = $Install | ConvertTo-Json;
            foreach ( $Os in $Data.os ) {
              $Include += @{
                label = $Os.label
                name = "'$($Install.id)' on $($Os.name)"
                run = ".\tests\install.ps1 '$Target'"
              };
            }
          }

          $Matrix = (@{ include = $Include } | ConvertTo-JSON) -replace '\n';
          $JSON = "matrix=$Matrix";

          echo $JSON;
          echo $JSON | Out-File -FilePath $env:GITHUB_OUTPUT -Append -Encoding utf8;

  test:
    needs: [build, generation]

    strategy:
      fail-fast: false
      matrix: ${{ fromJson( needs.generation.outputs.matrix ) }}

    runs-on: ${{ matrix.label }}

    name: ${{ matrix.name }}

    steps:
      - uses: actions/checkout@v4

      - name: Download app
        uses: actions/download-artifact@v4
        with:
          name: build
          path: output

      - name: Running scenario
        run: ${{ matrix.run }}
