name: E2e tests

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths-ignore:
      - '.**' # dot-dirs and dotfiles
      - '!.github/workflows/e2e-tests.yaml'
      - '!.mage'
      - 'innosetup/**'
      - '*.md'
      - 'LICENSE'
      - '*.iss'
      - '*.conf'
      - 'pslint.ps1'

jobs:
  build:
    name: Build

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup GO
        uses: .github/actions/setup-go.yaml

      - name: Build project
        run: .\run.ps1 build

      - name: Save cache
        if: always()
        uses: .github/actions/save-cache.yaml

      - name: Upload app
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: output

  test:
    needs: build

    strategy:
      fail-fast: true
      matrix:
        target:
          - os: windows-2025
            scenario: install
          - os: windows-2025
            scenario: not-found
          - os: windows-2025
            scenario: no-color
          - os: windows-2022
            scenario: install
          - os: windows-11-arm
            scenario: install

    runs-on: ${{ matrix.target.os }}

    name: ${{ matrix.target.scenario }} (${{ matrix.target.os }})

    steps:
      - uses: actions/checkout@v4

      - name: Download app
        uses: actions/download-artifact@v4
        with:
          name: build
          path: output

      - name: Running scenario
        run: .\tests\${{ matrix.target.scenario }}.ps1
