name: Lint and test

on:
  pull_request:

jobs:
  lint-and-test:
    runs-on: windows-latest

    name: Lint and test project

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: false

      - uses: arduino/setup-task@v2

      - name: Setup staticcheck@latest
        run: |
          go install "honnef.co/go/tools/cmd/staticcheck@latest"
          echo "$(go env GOPATH)/bin/staticcheck" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Lint project
        run: task lint

      - name: Run unit tests
        run: task test
