name: Lint and test

on:
  pull_request:
    paths-ignore:
      - '.vscode/**'
      - '.idea/**'
      - 'icons/**'

jobs:
  lint-and-test:
    runs-on: windows-latest

    name: Lint and test project

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: false

      - name: Setup staticcheck@latest
        run: |
          go install "honnef.co/go/tools/cmd/staticcheck@latest"
          echo "$(go env GOPATH)/bin/staticcheck" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Format project
        run: .\run.ps1 format

      - name: Lint project
        run: .\run.ps1 lint

      - name: Run unit tests
        run: .\run.ps1 test
