name: Check PowerShell scripts

on:
  pull_request:
    branches:
      - 'main'
    paths:
      - '.github/workflows/ps-check.yaml'
      - '**.ps1'

jobs:
  check-scripts:
    name: Check and test scripts

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Scripts check
        run: .\pslint.ps1
