name: Release

on:
  push:
    branches:
      - 'main'
    tags:
      - "*"

jobs:
  release:
    runs-on: windows-latest

    permissions:
      contents: write

    name: Build and release project

    steps:
    - uses: actions/checkout@v4

    - name: Set Inno Setup path
      id: iscc-path
      run: |
        $Path = "${env:TEMP}\inno"
        echo "Path: $Path"
        echo "path=$Path" >> $ENV:GITHUB_OUTPUT

    - id: init
      uses: ./.github/actions/init
      with:
        path: ${{ steps.iscc-path.outputs.path }}
        files: './iscc'

    - name: Set Inno Setup info
      id: iscc-info
      run: |
        $Test = "${{ steps.iscc-path.outputs.path }}" | Test-Path
        $Result = ([string]$Test).ToLower()
        echo "Installed: $Result"
        echo "is-installed=$Result" >> $ENV:GITHUB_OUTPUT
        $Version = cat .\iscc
        echo "Version: $Version"
        echo "version=$Version" >> $ENV:GITHUB_OUTPUT

    - uses: pwall2222/inno-setup-download@v0.0.8
      if: ${{ steps.iscc-info.outputs.is-installed != 'true' }}
      with:
        version: ${{ steps.iscc-info.outputs.version }}

    - name: Build project
      run: .\run.ps1 build

    - name: Pack project
      run: .\run.ps1 pack

    - name: Release project
      uses: anton-yurchenko/git-release@v6
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: release/*

    - uses: ./.github/actions/teardown
      with:
        path: ${{ steps.init.outputs.path }}
        key: ${{ steps.init.outputs.key }}
