name: Release

on:
  push:
    paths-ignore:
    - '.vscode/**'
    tags:
      - "*"

jobs:
  release:
    runs-on: windows-latest

    name: Build and release project

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'
        cache: false

    - uses: pwall2222/inno-setup-download@v0.0.8

    - name: Build project
      run: .\run.ps1 build

    - name: Release project
      uses: anton-yurchenko/git-release@v6
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: output/*
