name: Release

on:
  push:
    tags:
      - "*"

jobs:
  release:
    runs-on: windows-latest

    name: Build and release project

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'
        cache: false

    - name: Setup go-winres@latest
      run: |
        go install "github.com/tc-hib/go-winres@latest"
        echo "$(go env GOPATH)/bin/go-winres" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - name: Setup 7z@latest
      run: |
        Invoke-WebRequest -Uri https://7-zip.org/a/7zr.exe -OutFile .\7z.exe
        Join-Path ((Get-Location).Path) "7z.exe" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - uses: pwall2222/inno-setup-download@v0.0.8

    - name: Build project
      run: .\run.ps1 build

    - name: Release project
      uses: anton-yurchenko/git-release@v6
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: release/*
