name: Release

on:
  push:
    tags:
      - "*"

jobs:
  release:
    name: Build and release project

    runs-on: windows-latest

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - name: Setup GO
      uses: ./.github/actions/setup-go

    - name: Download Inno Setup
      uses: pwall2222/inno-setup-download@v0.0.8

    - name: Build project
      run: .\run.ps1 build

    - name: Pack project
      run: .\run.ps1 pack

    - name: Save cache
      if: always()
      uses: ./.github/actions/save-cache

    - name: Release project
      uses: anton-yurchenko/git-release@v6
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: release/*
