name: Remove old Pull Requests cache

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  clear:
    name: Remove old Pull Requests cache

    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

#          $ClosedPRs = gh pr list --state closed --json | ConvertFrom-Json
#          gh pr list --state closed
#          gh cache list --ref refs/pull/<number>/merge
      - name: List
        run: |
          gh cache list --ref refs/pull/1/merge
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
