name: Remove old Pull Requests cache

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  clear:
    name: Remove old Pull Requests cache

    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: List
        run: |
          $ClosedPRs = gh pr list --state closed --json | ConvertFrom-Json;
          foreach ( $PR in $ClosedPRs ) {
            echo "Pr $($PR.id) '$($PR.title)'"
            $PRCaches = gh cache list --ref refs/pull/$($PR.id)/merge | ConvertFrom-Json;
            echo $PRCaches;
          }
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
