name: Remove old Pull Requests cache

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  clear:
    name: Remove old Pull Requests cache

    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: List
        run: |
          closed_prs=$(gh pr list --state closed --json)

          while IFS= read -r pr; do
            pr_id=$(echo "$pr" | jq -r '.id')
            pr_title=$(echo "$pr" | jq -r '.title')
            echo "Pr $pr_id '$pr_title'"

            pr_caches=$(gh cache list --ref "refs/pull/$pr_id/merge" --json)
            echo "$pr_caches"
          done <<< "$(echo "$closed_prs" | jq -c '.[]')"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
