name: Remove old Pull Requests cache

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  clear:
    name: Remove old Pull Requests cache

    runs-on: ubuntu-24.04

    steps:
      - name: List
        run: |
          gh cache list
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
